### ISSUE TITLE
make the sticky note look like an actual post it

### ISSUE THREAD

**Issue by larsenwald** [larsenwald/Sticky-Notes-Extension#3]
- lighter header to mimic the adhesive strip of typical post its
- fix any kinks that comes with this change ^

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the CSS to add a lighter header to the sticky note, mimicking the adhesive strip of typical post-it notes. Adjusted other styles to ensure compatibility with this change.

You can review changes in this commit: https://github.com/jjyutm4532/larsenwald-Sticky-Notes-Extension-3/commit/244a14a6303f131a87fd3750330591d5d0168246.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
